export const KEY_TAX_ID = "taxidCopr"
export const KEY_NAME_COPR = "nameCopr"
export const KEY_ADDRESS = "addressCopr"
export const KEY_PHONE_NUMBER = "phoneNumberCopr"
export const KEY_EMAIL = "emailCopr"