export const PRODUCT = "PRODUCT"
export const PAYMENT = "PAYMENT"
export const TECHNOLOGY  = "TECHNOLOGY"
export const ASSURANCE_COMPENSATION  = "ASSURANCE_COMPENSATION"
export const CUSTOMER_SERVICE  = "CUSTOMER_SERVICE"
export const FEEDBACK  = "FEEDBACK"
export const OTHER  = "OTHER"
export const _currenAvatar = "https://sit2.inon.vn/resources/images/default-user-avatar.png"